packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages-internal/*'
  - 'docs'
    # - 'benchmark'
  # - 'packages/mui-envinfo/test'
  # - 'test'

catalog:
  react: ^18.3.1
  react-dom: ^18.3.1
  '@types/react': ^18.3.12
  '@types/react-dom': ^18.3.1
