export { default as deepmerge } from './deepmerge';
export { isPlainObject } from './deepmerge';
export { default as mergeStyles } from './mergeStyles';
export { default as unstable_capitalize } from './capitalize';
export { default as unstable_generateUtilityClass } from './generateUtilityClass';
export { isGlobalState as unstable_isGlobalState } from './generateUtilityClass';
export * from './generateUtilityClass';
export { default as unstable_generateUtilityClasses } from './generateUtilityClasses';
export { default as unstable_useForkRef } from './useForkRef';
export { default as unstable_useLazyRef } from './useLazyRef';
export { default as unstable_setRef } from './setRef';
export { default as unstable_useEnhancedEffect } from './useEnhancedEffect';
export { default as unstable_useEventCallback } from './useEventCallback';
export { default as unstable_isFocusVisible } from './isFocusVisible';
export { default as internal_resolveProps } from './resolveProps';
export { default as unstable_ClassNameGenerator } from './ClassNameGenerator';
export { default as unstable_useTimeout, Timeout as unstable_Timeout } from './useTimeout';
export { default as unstable_useOnMount } from './useOnMount';
